[tool.poetry]
name = "Team EaseMed"
version = "0.1.0"
description = "This is our repo for our EaseMed"
authors = ["EaseMed"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
